version: '3.8'
services:
#  app:
#    container_name: sc-internacional
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mongo
#    environment:
#      - MONGO_URI=mongodb://mongo:27017
#      - DB_NAME=sc-internacional
#    networks:
#      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: sc-internacional
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://mongo:27017"

volumes:
  mongo-data: