### Create a team
POST {{host}}/teams
Content-Type: application/json

{
  "name": "Internacional",
  "fullName": "Sport Club Internacional",
  "website": "internacional.com.br",
  "foundationDate": "1909-04-04T00:00:00Z"
}

> {% client.global.set("team_id", response.body.id); %}

### Get a team
GET {{host}}/teams/6702d8318c2dc4e05baf5c86

### Get All teams
GET {{host}}/teams